### PR TITLE
add CoinOptServices.jl to solver table

### PR DESCRIPTION
**Pull request by tkelman**
hopefully I html'ed this right

### CODE REVIEW

**Comment by mlubin** [comment]
We actually may want to list the real solvers instead of OS.

**Comment by tkelman** [comment]
Good point. Should I add a footnote or something to say "via osil files and OSSolverService," or just list Bonmin and Couenne under MINLP and make the link point to CoinOptServices?

**Comment by tkelman** [comment]
There's kind of a new category of "MathProgBase solver packages that convert to some other format" here, between this and AmplNLWriter.

OSSolverService can also talk to some of the less-widely-used COIN solvers like Symphony, Dip, Vol, etc, but so far my BinDeps only installs those on Linux.

**Comment by IainNZ** [comment]
I'll refine it, thanks

**Pull request merged**
