### PR TITLE
New reference to paper using JuliaOpt packages

### PR DESCRIPTION
**Pull request by rasmusbrandt**
I've added a link to one of my papers, appearing at IEEE CAMSAP'15. In the spirit of reproducible research, there is a link to the source code as well.

The paper uses `Convex.jl` and `Mosek.jl`, which are also cited in the paper appendix.

### CODE REVIEW

**Comment by mlubin** [comment]
Thanks!
CC @madeleineudell

**Comment by rasmusbrandt** [comment]
:+1:

**Comment by madeleineudell** [comment]
Cool!

On Fri, Oct 23, 2015 at 9:12 AM, Rasmus Brandt <notifications@github.com>
wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/juliaopt.org/pull/24#issuecomment-150584348>.
>



-- 
Madeleine Udell
Postdoctoral Fellow at the Center for the Mathematics of Information
California Institute of Technology
www.stanford.edu/~udell
(415) 729-4115

**Comment by madeleineudell** [comment]
Looking at your paper briefly, I see you also mentioned heuristically solving nonconvex (but multiconvex) problems using block coordinate descent. If you're interested in easy ways of doing that, you might want to take a look at [multiconvex.jl](https://github.com/madeleineudell/MultiConvex.jl).

**Comment by rasmusbrandt** [comment]
Cool, I wasn't aware of the MultiConvex package. I'll have it in mind for any future code I might write. Thanks!

**Pull request merged**
